import type { Metadata } from "next";
import { ContactForm } from "@/components/contact-form";
import { GraphUniverse } from "@/components/graph-universe";
import { GraverseMark } from "@/components/mark";
import { PublicationExplorer } from "@/components/publication-explorer";

export const metadata: Metadata = { title: "Graverse Lab — Türkçe", description: "Ege Üniversitesi'nde çizge kuramı, algoritmalar, ağ bilimi ve çizge merkezli yapay zekâ araştırma laboratuvarı." };

const areas = [
  ["01","Çizge kuramı","Ayrık sistemlerin nasıl düzenlendiğini ortaya çıkaran yapısal, ekstremal ve algoritmik sorular.",["Bağlantılılık","Baskınlık","Çizge boyama"]],
  ["02","Güvenilir ağlar","Bağlantılılık, süper bağlantılılık, dayanıklılık ve ara bağlantı ağlarında hata toleransı.",["Güvenilirlik","Hata toleransı","Ağ topolojisi"]],
  ["03","Algoritmalar ve optimizasyon","Çizgeler, ağlar ve ayrık yapılar üzerindeki güç problemler için kombinatoryal yöntemler.",["Kombinatoryal optimizasyon","Karmaşıklık","Algoritmalar"]],
  ["04","Çizge merkezli yapay zekâ","İlişkisel yapıyı temel bilgi kaynağı olarak kullanan öğrenme ve erişim sistemleri.",["Çizge sinir ağları","GraphRAG","Bilgisayarlı görü"]],
] as const;

export default function TurkishHome(){return <main><header className="site-header"><a href="#top" className="brand-link"><GraverseMark size={44}/><strong>GRAVERSE</strong></a><nav aria-label="Ana navigasyon"><a href="#research">Araştırma</a><a href="#projects">Projeler</a><a href="#publications">Yayınlar</a><a href="#people">Ekip</a><a href="#resources">Kaynaklar</a></nav><div className="header-actions"><a className="language" href="/" aria-label="Switch to English">TR <span>/ EN</span></a><a className="header-cta" href="#contact">İş birliği</a></div></header>
<section className="hero" id="top"><div className="hero-copy"><p className="kicker"><span>Araştırma laboratuvarı</span></p><h1>Çizgelerin<br/><em>evrenini keşfediyoruz.</em></h1><p className="hero-lead">Graverse Lab; titiz matematiği dayanıklı gerçek dünya sistemleriyle buluşturarak çizge kuramı, algoritmalar, ağ bilimi ve çizge merkezli yapay zekâyı ileri taşır.</p><div className="hero-actions"><a className="button primary" href="#research">Evrene gir <span>↗</span></a><a className="text-link" href="#publications">Yayınlarımızı incele →</a></div><div className="hero-meta"><div><span>Laboratuvar yürütücüsü</span><strong>Gülnaz Boruzanlı Ekinci</strong></div><div><span>Temel alanlar</span><strong>Çizgeler · Ağlar · Yapay zekâ</strong></div></div></div><GraphUniverse locale="tr"/></section>
<section className="manifesto"><span className="section-number">00 / Manifesto</span><p>Her karmaşık sistem ardında bir çizge bırakır. Biz onun yapısını inceler, sınırlarını sınar ve bağlantıları <em>anlaşılır, güvenilir ve yararlı</em> kılan yöntemler geliştiririz.</p></section>
<section className="research section-shell" id="research"><div className="section-heading"><span className="section-number">01 / Araştırma evreni</span><h2>Birbirine bağlı<br/>dört araştırma alanı.</h2><p>Araştırmalarımız matematiksel temeller ile hesaplamalı sistemler arasında ilerler.</p></div><div className="research-list">{areas.map(([index,title,description,topics])=><article className="research-row" key={title}><span className="row-index">{index}</span><div><h3>{title}</h3><p>{description}</p></div><ul>{topics.map(topic=><li key={topic}>{topic}</li>)}</ul><a href="#contact" aria-label={`${title} alanında iş birliği`}>↗</a></article>)}</div></section>
<section className="projects section-shell dark-section" id="projects"><div className="section-heading compact"><span className="section-number">02 / Seçili yönelimler</span><h2>Yapısal etkisi<br/>olan sorular.</h2></div><div className="project-grid"><article className="project-card featured"><span>Güvenilirlik · Çizge kuramı</span><h3>Bir ağ ne kadar arızaya dayanabilir?</h3><p>Kesinti altında çalışması beklenen sistemler için yeni bağlantılılık ölçütleri ve çizge modelleri.</p><a href="#contact">İş birliği yap →</a></article><article className="project-card"><span>Bilgi sistemleri · Yapay zekâ</span><h3>Güvenilir erişim için GraphRAG</h3><p>Teknik bilginin ölçekli kullanımı için ilişkisel erişim ve değerlendirme yöntemleri.</p></article><article className="project-card"><span>Çizge öğrenmesi</span><h3>Yapı duyarlı zekâ</h3><p>Çizge biçimli verinin matematiksel düzenini koruyan öğrenme sistemleri.</p></article></div></section>
<section className="publications section-shell" id="publications"><div className="section-heading horizontal"><div><span className="section-number">03 / Yayınlar</span><h2>Güncel çalışmalar.</h2></div><a className="text-link" href="https://dblp.org/pid/179/3810.html">Tüm kayıtları görüntüle ↗</a></div><PublicationExplorer locale="tr"/></section>
<section className="people section-shell" id="people"><div className="section-heading"><span className="section-number">04 / İnsanlar</span><h2>Kuruluş aşamasındaki bir laboratuvar.</h2><p>Graverse; çizgeler, ağlar ve yapay zekâ arasında matematiksel temelli bir araştırma topluluğu kuruyor.</p></div><article className="pi-card"><div className="portrait-placeholder"><GraverseMark compact/></div><div><span>Laboratuvar yürütücüsü</span><h3>Gülnaz Boruzanlı Ekinci</h3><p>Ege Üniversitesi · Matematik Bölümü</p><a href="mailto:gulnaz.boruzanli@ege.edu.tr">gulnaz.boruzanli@ege.edu.tr ↗</a></div></article><div className="formation-note"><span>Lisansüstü araştırmacılar</span><p>Üye profilleri laboratuvar topluluğu şekillendikçe duyurulacaktır.</p></div></section>
<section className="resources section-shell" id="resources"><span className="section-number">05 / Açık kaynaklar</span><div className="resource-marquee"><span>KOD</span><i>·</i><span>VERİ</span><i>·</i><span>POSTER</span><i>·</i><span>DERS</span></div><p>Tekrarlanabilir araştırma açık olmalıdır. Kod, veri setleri, posterler, sunumlar ve ders materyalleri hazır oldukça burada yayımlanacaktır.</p><article className="poster-card"><a className="poster-preview" href="/posters/social-network-centrality-2209a.pdf" target="_blank" rel="noreferrer"><img src="/posters/social-network-centrality-2209a-preview.png" alt="Ege Üniversitesi araştırma ağının çizge tabanlı merkezlik analizini gösteren akademik poster önizlemesi"/></a><div className="poster-details"><span className="resource-type">Poster · TÜBİTAK 2209-A</span><h3>Sosyal Ağlarda Merkezlik Analizleri İçin Çizge Tabanlı Bir Yaklaşım ve Ege Üniversitesi Araştırma Ağı Analizi</h3><p>Bahtınur Şener, Esma Yeter Sayındı ve Melisa Daş · Danışman: Gülnaz Boruzanlı Ekinci</p><div className="poster-actions"><a className="button primary" href="/posters/social-network-centrality-2209a.pdf" target="_blank" rel="noreferrer">Posteri görüntüle <span>↗</span></a><a className="text-link" href="/posters/social-network-centrality-2209a.pdf" download>PDF indir ↓</a></div></div></article></section>
<section className="contact" id="contact"><div><span className="section-number">06 / Bağlantı kur</span><h2>Zor bir çizge<br/>problemi getir.</h2></div><div className="contact-copy"><p>Araştırma ortaklıklarına, fonlanan proje konsorsiyumlarına, lisansüstü başvurulara ve sanayi iş birliklerine açığız.</p><ContactForm locale="tr"/></div></section>
<footer><GraverseMark/><p>Çizge Kuramı, Algoritmalar ve Ağ Bilimi</p><div><a href="mailto:gulnaz.boruzanli@ege.edu.tr">E-posta</a><a href="https://github.com/gboruzanli/graverse">GitHub</a><span>© {new Date().getFullYear()}</span></div></footer></main>}
