import Link from "next/link";
import { GraphVerseMonogram, OrbitalG, ResilientGraph } from "@/components/logo-concepts";
import "./brand.css";

const concepts = [
  { id:"A", name:"Orbital G", descriptor:"Graph + Universe", rationale:"A mathematical G becomes an open orbit. Two nodes establish the graph without turning the mark into a generic network icon.", strengths:["Distinctive at small sizes","Strong motion potential","Direct link to the name"], Mark:OrbitalG },
  { id:"B", name:"Resilient Graph", descriptor:"Connectivity + Reliability", rationale:"A structurally redundant network built around a central node, foregrounding connectivity, super-connectivity, and fault-tolerant systems.", strengths:["Scientifically grounded","Symmetric and institutional","Works as a research seal"], Mark:ResilientGraph },
  { id:"C", name:"Graph/Verse", descriptor:"G + V Monogram", rationale:"A compact G and V share one geometric structure. The result is abstract and editorial, suited to an international research identity.", strengths:["Ownable monogram","Editorial character","Strong in print"], Mark:GraphVerseMonogram },
] as const;

export default function BrandPage(){return <main className="brand-lab"><header className="brand-lab-header"><Link href="/">← Back to prototype</Link><span>Graverse Lab · Identity study 01</span></header><section className="brand-intro"><span className="section-number">Graph + Universe</span><h1>One identity.<br/><em>Three hypotheses.</em></h1><p>Each direction is a real vector system—not a generated picture—so it can become a favicon, publication mark, website signature, poster seal, or animated research object.</p></section><section className="concept-grid">{concepts.map(({id,name,descriptor,rationale,strengths,Mark})=><article className="concept-card" key={id}><div className="concept-visual"><Mark/></div><div className="concept-copy"><span>{id} / {descriptor}</span><h2>{name}</h2><p>{rationale}</p><ul>{strengths.map(s=><li key={s}>{s}</li>)}</ul></div><div className="concept-wordmark"><Mark/><div><strong>GRAVERSE</strong><small>LAB</small></div></div><div className="concept-micro"><Mark/><span>16 px</span><Mark/><span>32 px</span></div></article>)}</section><section className="brand-tests"><div><span className="section-number">Reproduction test</span><h2>A logo must survive<br/>without its colors.</h2></div><div className="mono-row">{concepts.map(({id,Mark})=><div key={id}><Mark/><span>{id}</span></div>)}</div></section><footer className="brand-decision"><span>Recommended direction</span><strong>A / Orbital G</strong><p>It balances scientific specificity, memorability, animation potential, and the Graph + Universe origin story most effectively.</p></footer></main>}
